# ~/Library/Preferences/rustfmt/.rustfmt.toml

unstable_features = true

max_width = 80
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
# struct_lit_single_line = false
use_small_heuristics = "Max"
struct_lit_width = 48
fn_single_line = true
# single_line_if_else_max_width = 100

edition = "2018"
